name: MacOS_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        /bin/bash ./install
        echo "Current working directory:"
    - name: test post install
      run: |
        pwd
        . ./activate && python --version
