name: Ubuntu_Remote_Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        rm -rf *
        curl https://raw.githubusercontent.com/zackees/install.py/main/setup.py -o setup.py
        curl -s https://raw.githubusercontent.com/zackees/install.py/main/install | bash
        . ./activate && python --version
