name: Ubuntu_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        /bin/bash ./install
        . ./activate && python --version
